# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TPInAppReceiptiOSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TPInAppReceiptiOSDemo
  pod 'TPInAppReceiptX', :path => '..'

end
